---
- hosts: all
  become: yes
  tasks:
     - name: change line in file
       lineinfile:
           state: present
           dest: /etc/ssh/sshd_config
           regexp: "^PasswordAuthentication"
           line: "PasswordAuthentication yes"
           validate: "sshd -t -f %s"
            
