---
- hosts: all
  gather_facts: yes
       
  tasks:  
        
    - name: add docker apt repository
      become: yes
      apt_repository: 
         repo: deb [arch = "{{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else 'i386' }}" ] https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable
         state: present 
          
          
       
