---
- hosts: all
  become: yes
  gather_facts: no
  tasks :
          - name: update package cache
            apt: 
               update_cache: true
               
- hosts: ubuntu
  become: yes
  gather_facts: no
  tasks :
          - name: install nginx
            apt: 
              name: nginx
              state: present
