---
               
- hosts: ubuntu
  gather_facts: no
  tasks :
          - name: install nginx
            become: yes
            apt: 
              name: nginx
              state: present
            
          - name : copy nginx config file 
            become: yes
            copy:
                    src: nginx.conf 
                    dest: /etc/nginx/nginx.conf
            
            notify: 
                 - restart nginx

  handlers:
           - name: restart nginx
             become: yes
             systemd:
                  name: nginx
                  state: restarted                  
